### ISSUE TITLE
Gitea v1.9.0 images do not contain entrypoint

### ISSUE THREAD

**Issue by PKizzle** [Kunde21/raspberry-dev#3]
It seems like the uploaded images on Docker Hub do not contain the root folder from the Gitea repo with the entrypoint and configuration files. Could you please adjust the images to include them?

I was using version v1.9.0-rc2 for armhf.

**Comment by Kunde21** [comment]
Thank you, I missed the changed directory structure.  Fixed for v1.9.0 release containers.

**Comment by PKizzle** [comment]
Now everything works as expected. Problem solved :)
