### ISSUE TITLE
Gitea v1.11 UI in Docker is broken, missing CSS and JS resources 

### ISSUE THREAD

**Issue by amyspark** [Kunde21/raspberry-dev#4]
(reposted from https://github.com/go-gitea/gitea/issues/10448 as upstream directed me here)

- Gitea version (or commit ref): 1.11.1
- Git version: 2.24.1
- Operating system: Docker (kunde21/gitea-arm:v1.11.1)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description

I use Gitea through the `kunde21/gitea-arm:v1.11.1` image (ARMv7) under a Raspberry Pi 3 B+. Ever since I upgraded my services to the v1.11 images, the UI is broken, and the Dev Tools show HTTP 404 errors for `js/index.js?v=b7b0b0e0a539f1923ef5da163e614fa9` and `css/index.css?v=b7b0b0e0a539f1923ef5da163e614fa9`. Accessing these resources returns a HTTP 404 generated from within the container.

## Screenshots
![Captura de pantalla de 2020-02-24 17-34-33](https://user-images.githubusercontent.com/13498015/75189217-81700080-572c-11ea-9086-593487fb0fb1.png)

**Comment by Kunde21** [comment]
Thank you @amyspark.  Haven't gotten the chance to test this release, yet.  So, of course I broke it.  :laughing: 
I'll try to debug the build today.

**Comment by Kunde21** [comment]
Published the manifests with build changes from #5 and tested locally.  
@amyspark  Please try with the new images and let me know if that fixed it.

**Comment by amyspark** [comment]
With `kunde21/gitea-arm@sha256:b25e7e11af262992b09f739dc5cbf4fc8ad63ebd0af404755428f41a1f008b63`, it's still bugged.

**Comment by Kunde21** [comment]
New hash: `sha256:173b24ee0e6b107b41f5344ab04c12cdecbbba54007d4cc460918a91ed84eec4` I'm getting what looks right
![Screenshot from 2020-02-26 10-37-02](https://user-images.githubusercontent.com/10493268/75312887-4689dc00-5896-11ea-8987-789fff04c6fa.png)

If you're seeing any 404's for resources, please let me know
![Screenshot from 2020-02-26 10-36-55](https://user-images.githubusercontent.com/10493268/75312892-4984cc80-5896-11ea-9728-ecb69bf21c24.png)

**Comment by amyspark** [comment]
Confirmed, it's fixed now!

**Comment by Kunde21** [comment]
Great to hear!  Thanks again and enjoy :)
